name:                lambda-infobot
version:             0.1.0.0
github:              "Garmelon/lambda-infobot"
license:             BSD3
author:              "Joscha Mennicken"
maintainer:          "joscha@migejolise.de"
copyright:           "Joscha Mennicken"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Garmelon/lambda-infobot#readme>

dependencies:
- base >= 4.7 && < 5
- euph-api
- hslogger
- stm
- text

library:
  source-dirs: src

executables:
  lambda-infobot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-infobot

tests:
  lambda-infobot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-infobot
